=== hajdugaborA97C75/A97C75_XMLGyak/XMLTaskA97C75/elsofeladatA97C75/XMLSchemaA97C75.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="gyogyszertar_adatok">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="raktarak">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="raktar" type="raktarTipus" maxOccurs="unbounded" minOccurs="0" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="gyogyszertarak">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="gyogyszertar" type="gyogyszertarTipus" maxOccurs="unbounded" minOccurs="0" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="gyogyszertarvezetok">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="gyogyszertarvezeto" type="gyogyszertarvezetoTipus" maxOccurs="unbounded" minOccurs="0" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="dolgozok">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="dolgozo" type="dolgozoTipus" maxOccurs="unbounded" minOccurs="0" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="gyogyszerek">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="gyogyszer" type="gyogyszerTipus" maxOccurs="unbounded" minOccurs="0" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="vasarlok">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="vasarlo" type="vasarloTipus" maxOccurs="unbounded" minOccurs="0" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="gyogyszertar-raktar">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="szallitas" type="szallitasTipus" maxOccurs="unbounded" minOccurs="0" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="gyogyszertar-vasarlo">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="vasarlas" type="vasarlasTipus" maxOccurs="unbounded" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="vasarlo-gyogyszer">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="betegseg" type="betegsegTipus" maxOccurs="unbounded" minOccurs="0" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="gyogyszertar-gyogyszertarvezeto">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="vezetes" type="vezetesTipus" maxOccurs="unbounded" minOccurs="0" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="dolgozo-gyogyszertarvezeto">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="alkalmazott" type="alkalmazottTipus" maxOccurs="unbounded" minOccurs="0" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>

		<xs:key name="gyogyszertar_ID">
			<xs:selector xpath="gyogyszertar" />
			<xs:field xpath="@GysztID"></xs:field>
		</xs:key>
		<xs:key name="gyogyszertar_vezeto_ID">
			<xs:selector xpath="gyogyszertarvezeto" />
			<xs:field xpath="@GyvID"></xs:field>
		</xs:key>
		<xs:key name="dolgozo_ID">
			<xs:selector xpath="dolgozo" />
			<xs:field xpath="@DID"></xs:field>
		</xs:key>
		<xs:key name="raktar_ID">
			<xs:selector xpath="raktar" />
			<xs:field xpath="@RID"></xs:field>
		</xs:key>
		<xs:key name="vasarlo_ID">
			<xs:selector xpath="vasarlo" />
			<xs:field xpath="@VID"></xs:field>
		</xs:key>
		<xs:key name="gyogyszer_ID">
			<xs:selector xpath="gyogyszer" />
			<xs:field xpath="@GyszID"></xs:field>
		</xs:key>
		<xs:keyref refer="gyogyszertar_ID"
			name="vezetes-gyogyszertar">
			<xs:selector xpath="vezetes"></xs:selector>
			<xs:field xpath="@GysztID"></xs:field>
		</xs:keyref>
		<xs:keyref refer="gyogyszertar_vezeto_ID"
			name="vezetes-gyogyszertarvezeto">
			<xs:selector xpath="vezetes"></xs:selector>
			<xs:field xpath="@GyvID"></xs:field>
		</xs:keyref>
		<xs:keyref refer="raktar_ID" name="szallitas-raktar">
			<xs:selector xpath="szallitas"></xs:selector>
			<xs:field xpath="@RID"></xs:field>
		</xs:keyref>
		<xs:keyref refer="gyogyszertar_ID"
			name="szallitas-gyogyszertar">
			<xs:selector xpath="szallitas"></xs:selector>
			<xs:field xpath="@GysztID"></xs:field>
		</xs:keyref>
		<xs:keyref refer="gyogyszertar_vezeto_ID"
			name="alkalmazott-gyogyszertarvezeto">
			<xs:selector xpath="alkalmazott"></xs:selector>
			<xs:field xpath="@GyvID"></xs:field>
		</xs:keyref>
		<xs:keyref refer="dolgozo_ID" name="alkalmazott-dolgozo">
			<xs:selector xpath="alkalmazott"></xs:selector>
			<xs:field xpath="@DID"></xs:field>
		</xs:keyref>
		<xs:keyref refer="gyogyszertar_ID"
			name="vasarlas-gyogyszertar">
			<xs:selector xpath="vasarlas"></xs:selector>
			<xs:field xpath="@GysztID"></xs:field>
		</xs:keyref>
		<xs:keyref refer="vasarlo_ID" name="vasarlas-vasarlo">
			<xs:selector xpath="vasarlas"></xs:selector>
			<xs:field xpath="@VID"></xs:field>
		</xs:keyref>
		<xs:keyref refer="gyogyszer_ID" name="betegseg-gyogyszer">
			<xs:selector xpath="betegseg"></xs:selector>
			<xs:field xpath="@GyszID"></xs:field>
		</xs:keyref>
		<xs:keyref refer="vasarlo_ID" name="betegseg-vasarlo">
			<xs:selector xpath="betegseg"></xs:selector>
			<xs:field xpath="@VID"></xs:field>
		</xs:keyref>
	</xs:element>

	<xs:element name="cim">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:short" name="iranyitoszam" />
				<xs:element type="xs:string" name="varos" />
				<xs:element type="xs:string" name="utca" />
				<xs:element type="xs:string" name="hazszam" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="receptre_kaphato">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Igen" />
				<xs:enumeration value="Nem" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="fizetesi_mod">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Bankkártya" />
				<xs:enumeration value="Készpénz" />
				<xs:enumeration value="SZÉP-kártya" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:simpleType name="id">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="1" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="munka_id">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z]+[A-Z]+[0-9]+[0-9]" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name='raktarTipus'>
		<xs:sequence>
			<xs:element ref="cim" />
			<xs:element type="xs:string" name="nev" />
		</xs:sequence>
		<xs:attribute type="id" name="RID" />
	</xs:complexType>

	<xs:complexType name='gyogyszertarTipus'>
		<xs:sequence>
			<xs:element ref="cim" />
			<xs:element type="xs:string" name="nev" />
		</xs:sequence>
		<xs:attribute type="id" name="GysztID" />
	</xs:complexType>

	<xs:complexType name='gyogyszertarvezetoTipus'>
		<xs:sequence>
			<xs:element ref="cim" />
			<xs:element type="xs:string" name="nev" />
		</xs:sequence>
		<xs:attribute type="munka_id" name="GyvID" />
	</xs:complexType>

	<xs:complexType name='dolgozoTipus'>
		<xs:sequence>
			<xs:element ref="cim" />
			<xs:element type="xs:string" name="nev" />
		</xs:sequence>
		<xs:attribute type="munka_id" name="DID" />
	</xs:complexType>

	<xs:complexType name="gyogyszerTipus">
		<xs:sequence>
			<xs:element ref="receptre_kaphato" />
			<xs:element type="xs:string" name="hatoanyag" />
			<xs:element type="xs:string" name="tipus" />
			<xs:element type="xs:string" name="nev" />
		</xs:sequence>
		<xs:attribute type="id" name="GyszID" />
	</xs:complexType>

	<xs:complexType name="vasarloTipus">
		<xs:sequence>
			<xs:element type="xs:string" name="nev" />
			<xs:element type="xs:string" name="haziorvos" />
			<xs:element type="xs:string" name="gyogyszererzekenyseg" />
		</xs:sequence>
		<xs:attribute type="id" name="VID" />
	</xs:complexType>

	<xs:complexType name="szallitasTipus">
		<xs:sequence>
			<xs:element type="xs:date" name="datum" />
			<xs:element type="xs:string" name="fuvarozo_ceg" />
			<xs:element type="xs:int" name="osszeg" />
			<xs:element type="id" name="GysztID" />
			<xs:element type="id" name="RID" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="vasarlasTipus">
		<xs:sequence>
			<xs:element type="xs:int" name="osszeg" />
			<xs:element ref="fizetesi_mod" />
			<xs:element type="id" name="GysztID" />
			<xs:element type="id" name="VID" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="betegsegTipus">
		<xs:sequence>
			<xs:element type="xs:string" name="panasz" />
			<xs:element type="id" name="VID" />
			<xs:element type="id" name="GyszID" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="vezetesTipus">
		<xs:sequence>
			<xs:element type="munka_id" name="GyvID" />
			<xs:element type="id" name="GysztID" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="alkalmazottTipus">
		<xs:sequence>
			<xs:element type="munka_id" name="GyvID" />
			<xs:element type="munka_id" name="DID" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== hajdugaborA97C75/A97C75_XMLGyak/XMLTaskA97C75/elsofeladatA97C75/XMLA97C75.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<gyogyszertar_adatok
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="XMLSchemaA97C75.xsd">

	<raktarak>
		<raktar RID="1">
			<cim>
				<iranyitoszam>3526</iranyitoszam>
				<varos>Miskolc</varos>
				<utca>Szentpéteri kapu</utca>
				<hazszam>47</hazszam>
			</cim>
			<nev>The Storage</nev>
		</raktar>
		<raktar RID="3">
			<cim>
				<iranyitoszam>3529</iranyitoszam>
				<varos>Miskolc</varos>
				<utca>Szentgyörgy út</utca>
				<hazszam>10</hazszam>
			</cim>
			<nev>MedStor</nev>
		</raktar>
	</raktarak>

	<gyogyszertarak>
		<gyogyszertar GysztID="12">
			<cim>
				<iranyitoszam>3526</iranyitoszam>
				<varos>Miskolc</varos>
				<utca>Szentpéteri kapu</utca>
				<hazszam>72-76</hazszam>
			</cim>
			<nev>Szent Péter gyógyszertár</nev>
		</gyogyszertar>
		<gyogyszertar GysztID="4">
			<cim>
				<iranyitoszam>3529</iranyitoszam>
				<varos>Miskolc</varos>
				<utca>Szentgyörgy út</utca>
				<hazszam>25</hazszam>
			</cim>
			<nev>Benu gyógyszertár</nev>
		</gyogyszertar>
	</gyogyszertarak>

	<gyogyszertarvezetok>
		<gyogyszertarvezeto GyvID="KP13">
			<cim>
				<iranyitoszam>3526</iranyitoszam>
				<varos>Miskolc</varos>
				<utca>Katowice</utca>
				<hazszam>14</hazszam>
			</cim>
			<nev>Dr. Kalapos Péter</nev>
		</gyogyszertarvezeto>
		<gyogyszertarvezeto GyvID="FZ02">
			<cim>
				<iranyitoszam>3529</iranyitoszam>
				<varos>Miskolc</varos>
				<utca>Áfonyás utca</utca>
				<hazszam>25</hazszam>
			</cim>
			<nev>Dr. Fekete Zoltán</nev>
		</gyogyszertarvezeto>
	</gyogyszertarvezetok>

	<dolgozok>
		<dolgozo DID="MF12">
			<cim>
				<iranyitoszam>3526</iranyitoszam>
				<varos>Miskolc</varos>
				<utca>Gömöri tér</utca>
				<hazszam>8</hazszam>
			</cim>
			<nev>Molnár Ferenc</nev>
		</dolgozo>
		<dolgozo DID="SM02">
			<cim>
				<iranyitoszam>3525</iranyitoszam>
				<varos>Miskolc</varos>
				<utca>Galagonyás sor</utca>
				<hazszam>1</hazszam>
			</cim>
			<nev>Soós Márton</nev>
		</dolgozo>
	</dolgozok>

	<gyogyszerek>
		<gyogyszer GyszID="6318">
			<receptre_kaphato>Nem</receptre_kaphato>
			<hatoanyag>metamizol-nátrium</hatoanyag>
			<tipus>fájdalom- és lázcsillapító, gyulladáscsökkentő</tipus>
			<nev>Algopyrin</nev>
		</gyogyszer>
		<gyogyszer GyszID="8113">
			<receptre_kaphato>Nem</receptre_kaphato>
			<hatoanyag>magnézium</hatoanyag>
			<tipus>Vitamin</tipus>
			<nev>Magnerot</nev>
		</gyogyszer>
	</gyogyszerek>

	<vasarlok>
		<vasarlo VID="983323">
			<nev>Hajdu Gábor</nev>
			<haziorvos>Dr. Lóránt Tibor</haziorvos>
			<gyogyszererzekenyseg>nincs</gyogyszererzekenyseg>
		</vasarlo>
		<vasarlo VID="64531">
			<nev>Horvát Róbert</nev>
			<haziorvos>Dr. Kovács Péter</haziorvos>
			<gyogyszererzekenyseg>metamizol-nátrium</gyogyszererzekenyseg>
		</vasarlo>
	</vasarlok>

	<gyogyszertar-raktar>
		<szallitas>
			<datum>2020-12-03</datum>
			<fuvarozo_ceg>DHL</fuvarozo_ceg>
			<osszeg>456000</osszeg>
			<GysztID>12</GysztID>
			<RID>1</RID>
		</szallitas>
		<szallitas>
			<datum>2020-11-10</datum>
			<fuvarozo_ceg>GLS</fuvarozo_ceg>
			<osszeg>123000</osszeg>
			<GysztID>4</GysztID>
			<RID>10</RID>
		</szallitas>
	</gyogyszertar-raktar>

	<gyogyszertar-vasarlo>
		<vasarlas>
			<osszeg>5300</osszeg>
			<fizetesi_mod>Bankkártya</fizetesi_mod>
			<GysztID>12</GysztID>
			<VID>983323</VID>
		</vasarlas>
		<vasarlas>
			<osszeg>12340</osszeg>
			<fizetesi_mod>Készpénz</fizetesi_mod>
			<GysztID>4</GysztID>
			<VID>64531</VID>
		</vasarlas>
	</gyogyszertar-vasarlo>

	<vasarlo-gyogyszer>
		<betegseg>
			<panasz>nincs</panasz>
			<VID>64531</VID>
			<GyszID>8113</GyszID>
		</betegseg>
		<betegseg>
			<panasz>fejfájás, láz</panasz>
			<VID>983323</VID>
			<GyszID>6318</GyszID>
		</betegseg>
	</vasarlo-gyogyszer>

	<gyogyszertar-gyogyszertarvezeto>
		<vezetes>
			<GyvID>KP13</GyvID>
			<GysztID>12</GysztID>
		</vezetes>
		<vezetes>
			<GyvID>FZ02</GyvID>
			<GysztID>4</GysztID>
		</vezetes>
	</gyogyszertar-gyogyszertarvezeto>

	<dolgozo-gyogyszertarvezeto>
		<alkalmazott>
			<GyvID>KP13</GyvID>
			<DID>MF12</DID>
		</alkalmazott>
		<alkalmazott>
			<GyvID>FZ02</GyvID>
			<DID>SM02</DID>
		</alkalmazott>
	</dolgozo-gyogyszertarvezeto>

</gyogyszertar_adatok>
