=== hajdugaborA97C75/A97C75_XMLGyak/A97C75_0928/HG_kurzusfelvetel.dtd
<?xml version="1.0" encoding="UTF-8"?

<!ELEMENT HG_kurzusfelvetel (hallgato,kurzusok)>
	<!ATTLIST HG_kurzusfelvetel
		tanev CDATA #REQUIRED
		egyetem CDATA #FIXED "ME">
<!ELEMENT hallgato (hnev,szulev,szak+)>
	<!ATTLIST hallgato
		id ID #REQUIRED>
<!ELEMENT hnev (#PCDATA)>
<!ELEMENT szulev (#PCDATA)>
<!ELEMENT szak (#PCDATA)>
<!ELEMENT kurzusok (kurzus+)>
<!ELEMENT kurzus (kurzusnev,kredit,hely,idopont,oktato,oraado*)>
	<!ATTLIST kurzus
		id ID #REQUIRED
		jovahagyas CDATA #IMPLIED
		nyelv CDATA #IMPLIED>
<!ELEMENT kurzusnev (#PCDATA)>
<!ELEMENT kredit (#PCDATA)>
<!ELEMENT hely (#PCDATA)>
<!ELEMENT idopont (#PCDATA)>
<!ELEMENT oktato (#PCDATA)>
<!ELEMENT oraado (#PCDATA)>

=== hajdugaborA97C75/A97C75_XMLGyak/A97C75_1005/HG_kurzusfelvetel.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE HG_kurzusfelvetel SYSTEM "HG_kurzusfelvetel.dtd">

<HG_kurzusfelvetel tanev="2022_2023 I." egyetem="ME">
	<hallgato id="A97C75.ME">
		<hnev>Hajdu Gábor</hnev>
		<szulev>2000-03-15</szulev>
		<szak evf="5">Programtervező informatikus</szak>
	</hallgato>
	
	<kurzusok>

		<kurzus id="GEIAL332-B">
			<kurzusnev>Adatkezelés XML környezetben</kurzusnev>
			<kredit>5</kredit>
			<hely>XXXII</hely>
			<idopont>Kedd 12:00-14:00</idopont>
			<oktato>Dr. Bednarik László</oktato>
		</kurzus>
		
		<kurzus id="GEMAK234-B" jovahagyas="igen">
			<kurzusnev>Algoritmusok és vizsgálatuk</kurzusnev>
			<kredit>5</kredit>
			<hely>X</hely>
			<idopont>Kedd 14:00-18:0</idopont>
			<oktato>Dr. Házy Attila</oktato>
		</kurzus>
		
		<kurzus id="GEIAL332-B">
			<kurzusnev>Adatkezelés XML környezetben</kurzusnev>
			<kredit>5</kredit>
			<hely>In101</hely>
			<idopont>Szerda 12:00-14:00</idopont>
			<oktato>Dr. Bednarik László</oktato>
		</kurzus>
		
		<kurzus id="GEIAL315-B" nyelv="angol">
			<kurzusnev>Vállalati információs rendszerek fejlesztése</kurzusnev>
			<kredit>5</kredit>
			<hely>In103</hely>
			<idopont>Szerda 16:00-20:00</idopont>
			<oktato>Dr. Sasvári Péter</oktato>
		</kurzus>
	
	</kurzusok>

</HG_kurzusfelvetel>
